### PR TITLE
Add Unicode support

### PR DESCRIPTION
**Pull request by greyli**

### CODE REVIEW

**Comment by bkabrda** [comment]
Hi,
first of all, thanks for taking the time to do this PR and sorry for my late response.
I have to admit I'm not sure what's the usecase of this - is it to transform a potentially non-unicode Python 2 string to a unicode object or is it to get a textual representation of potentially non-string object? I don't think that whooshee should support the second case. As for the first one, I'd need to give it a thought, but I think it shouldn't be necessary on Python 2 and it doesn't work on Python 3 (see the failed travis tests).

Also, it seems that travis is failing for Python 2.6 branch, but that's unrelated to this PR, so feel free to disregard that.

**Comment by greyli** [comment]
Sorry I didn't explain this thing. 

I got a `UnicodeDecodeError: 'ascii' codec can't decode byte... ` when I try to search Non-English query, I add this to make it work. I thought it was kind of indexes problem (similar to [this](https://bitbucket.org/mchaput/whoosh/issues/395/ascii-codec-error-when-performing-query)), but I can't reproduce the error now.

**Comment by bkabrda** [comment]
Ok, thanks, I managed to reproduce it - the problem is in the same function you're patching, few lines below - `s = u'*{0}*'.format(re.sub('[\s]+', '* *', s))` - the issue here is that if a `str` object is passed, Python 2 tries to interpolate the `s` into the unicode string using the `ascii` codec. So if `s` contains non-ascii chars, this obviously fails.

For me, trying to use your solution fails as well, but I came up with following patch that seems to work ok [1] - could you verify that it works ok for you? If so, I'll use it to fix the issue.

Thanks!

[1] https://paste.fedoraproject.org/paste/3b2kAJqIeCnxtYhwYBLTlg

**Comment by bkabrda** [comment]
Ok, cool, thanks. I'll commit my patch then. Either way, thanks for working on this!

**Comment by bkabrda** [comment]
Fixed in https://github.com/bkabrda/flask-whooshee/commit/13d8272a9c1fc33e142acbf30ecbb9db5336f5ff

**Comment by bkabrda** [comment]
Released as part of flask-whooshee 0.5.0: https://pypi.python.org/pypi/flask-whooshee/0.5.0

**Comment by greyli** [comment]
Sorry to disturb you, it seems that the problem still exists on 0.5.0. When I search with non-ascii string, I got this:
```pytb
  File "C:\Users\Administrator\projects\albumy\albumy\main\views.py", line 56, in search
    pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
  File "C:\Users\Administrator\.virtualenvs\albumy-aCIvDf20\lib\site-packages\flask_whooshee.py", line 90, in whooshee_search
    limit=limit)
  File "C:\Users\Administrator\.virtualenvs\albumy-aCIvDf20\lib\site-packages\flask_whooshee.py", line 153, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "C:\Users\Administrator\.virtualenvs\albumy-aCIvDf20\lib\site-packages\flask_whooshee.py", line 171, in prep_search_string
    search_string = search_string.decode('utf-8')
  File "C:\Users\Administrator\.virtualenvs\albumy-aCIvDf20\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```
However, with this pr everything worked.

**Comment by greyli** [comment]
Any ideas? @bkabrda

**Comment by greyli** [comment]
Hi, @bkabrda, what need I do to make this PR merged?

**Pull request closed without merging**
