### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by frenzymadness**
New flexmock has some breaking changes and no longer supports Python 2. On the other hand, nose is not compatible with Python 3.10.

### CODE REVIEW

**Comment by frenzymadness** [comment]
It seems that this project needs to migrate its CI config to either new Travis CI or to Github Action. In the case of Gitbub actions I'd recommend testing of Fedora with all available Pythons, see: https://github.com/fedora-python/tox-github-action

**Comment by praiskup** [comment]
Would you mind adding another commit with `.github/workflows/somefile.yml` making Github Actions work?

**Comment by frenzymadness** [comment]
The config for tox and github actions added - I'm using special action to run the tests on Fedora where we deliver the latest Pythons sooner than others. I've pushed the same content into my master branch so you can see it running: https://github.com/frenzymadness/flask-whooshee/actions/runs/1484825348

**Comment by praiskup** [comment]
@bkabrda can you please enable GitHub Actions here?

**Comment by frenzymadness** [comment]
This should not be needed. Once we merge this, the tests should run on master branch and every new pull request.

**Comment by praiskup** [comment]
Weird, according to my experience with GH actions, they work just fine from the first PR ([example](https://github.com/praiskup/resalloc/pull/65))

**Comment by frenzymadness** [comment]
I didn't have to do anything special in my fork - just pushed the yaml file to the master branch. It's verified in my fork anyway so we can just merge this and see what happens next.

**Comment by frenzymadness** [comment]
All green in master!

**Comment by praiskup** [comment]
Indeed, thank you again!

**Pull request merged**
