### PR TITLE
Release 0.9.1 version

### PR DESCRIPTION
**Pull request by greyli**
* Fix outdated URLs
* Bump version number to 0.9.1

### CODE REVIEW

**Review by praiskup — APPROVED** [review]
Thank you!

**Comment by greyli** [comment]
Please help to make a new release for the 0.9.1 version. Thanks!

**Comment by greyli** [comment]
@xsuchy @praiskup Could you grant me the permission of PyPI for this project? I can help to make a new release.

**Comment by FrostyX** [comment]
@greyli Are you by any chance also a Fedora package maintainer? Or should we do the Fedora update once you push it to PyPI?

**Comment by praiskup** [comment]
@FrostyX what about trying the Packit's propose-downstream feature?

**Comment by FrostyX** [comment]
@praiskup Yeah, that would be ideal for this project.

**Comment by greyli** [comment]
> @greyli Are you by any chance also a Fedora package maintainer? Or should we do the Fedora update once you push it to PyPI?

I have pushed the package to [the PyPI](https://pypi.org/project/flask-whooshee/), but I know little about the Fedora package or Packit...

**Comment by praiskup** [comment]
@greyli we (Fedora packagers) can do that -> #88

**Pull request merged**
