### PR TITLE
Need to be able to use flask-whooshee using Flask init_app protocol

### PR DESCRIPTION
**Pull request by pjcunningham**

### CODE REVIEW

**Comment by bkabrda** [comment]
Very cool, thanks! Just a question - why does `BaseTest` need to be a nested class?

**Comment by pjcunningham** [comment]
Hello Slavek,

I'm a Python newbie - I took guidance from: http://stackoverflow.com/a/25695512/2800058

Maybe you have a stronger opinion on how the tests should be organised - please change/correct as you see fit,

Regards, Paul.

**Comment by bkabrda** [comment]
Oh, I see. I actually usually work with pytest, which doesn't have this sort of issues, so this wasn't obvious to me on the first look. I understand now and I'm merging. Thanks a lot!

**Comment by bkabrda** [comment]
Released as 0.0.7, feel free to give it a try: https://pypi.python.org/pypi/flask-whooshee/0.0.7

**Pull request merged**
