### PR TITLE
Add RamStorage support

### PR DESCRIPTION
**Pull request by sh4nks**
Let me know if anything is missing :)

### CODE REVIEW

**Comment by bkabrda** [comment]
Thanks for another cool PR! Everything LGTM, there's just a Travis fail on Python 2.6, since `assertIsInstance` was added in 2.7 [1]. So once you replace that with something else that works on 2.6 as well, I'll merge.

[1] https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIsInstance

**Comment by sh4nks** [comment]
The tests should be fixed now :)

**Comment by bkabrda** [comment]
LGTM, merging. Thanks!

**Comment by bkabrda** [comment]
Released in https://pypi.python.org/pypi/flask-whooshee/0.4.1 - enjoy!

**Pull request merged**
