### PR TITLE
Fix for SQLAlchemy 1.4+ where is no _join_entities() attribute

### PR DESCRIPTION
**Pull request by praiskup**
Fixes: #60

### CODE REVIEW

**Comment by praiskup** [comment]
I still need to take a look at Travis builds (newer Python, etc.).  So please don't merge.

**Comment by sh4nks** [comment]
Travis is dead for open source projects - it would be better to move to GitHub Actions but that would be another issue imho :-)

**Comment by praiskup** [comment]
Actually, it still works to some extent ... @bkabrda can you give me admin access here?  Or at least reconfigure against travis-ci.com?

**Comment by praiskup** [comment]
Turns out I can not be added as admin here, so let's go without CI now.

**Pull request merged**
